modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://github.com/AtomicBlom/WeirdingGadget/issues" #optional
license="LGPL3"

[[mods]] #mandatory
    modId="weirdinggadget" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="The Weirding Gadget" #mandatory
    #updateJSONURL="http://myurl.me/" #optional
    displayURL="http://github.com/AtomicBlom/WeirdingGadget" #optional
    #logoFile="examplemod.png" #optional
    #credits="" #optional
    authors="AtomicBlom, Rorax" #optional
    description='''No idea what this does, but stuff happens when I'm not here.'''

[[dependencies.weirdinggadget]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.weirdinggadget]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
