@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.atomicblom.weirdinggadget.block.tileentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;