@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.atomicblom.weirdinggadget.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;