@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.atomicblom.weirdinggadget.registration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;