@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.atomicblom.weirdinggadget;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;